### ISSUE TITLE
No support for Update queries

### ISSUE THREAD

**Issue by tomar-mohit** [Yegoroff/PlainElastic.Net#85]
There is no update command specified. Neither in PlainElastic.Net.Commands, not can you do a ElasticConnection.Update or something like this. If you call POST or PUT command on any object/document, it gets replaced completely, that is the _source field gets replaced with the one you specified in the POST/PUT command.

As specified in 

http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/partial-updates.html

you must issue a  

_update

at the end of url so that it knows that we are partially updating the document and not completely replacing it, I have found no support for this.

**Comment by grafzahl1986** [comment]
i would like to see the code for your plainelastic extension to update a field of a document...
please mail me to marcoliver.vanlaack@cbc-extern.de
thank you very much
