### ISSUE TITLE
can you please update nuget package

### ISSUE THREAD

**Issue by alexdoan102** [Yegoroff/PlainElastic.Net#98]
Hi, 
 you update [Added support for https and a second option for the constructor], the sourcecode, but you never updated the nuget package... can u please update the nuget package?

**Comment by benfranklin79** [comment]
I'm away from my box for most of today so will do this either later today or tomorrow

**Comment by benfranklin79** [comment]
Actually I've taken a closer look at this and I did not do this change. I did the change for adding a timeout to the constructor. When I did that change you updated the package version for that shortly after I made the pull request. You need to contact https://github.com/o-e

**Comment by benfranklin79** [comment]
It was such a simple change I decided to do it myself. You should get a pull request

**Comment by Yegoroff** [comment]
Published 1.1.55
